name: Go Tests

on:
  push:
    paths:
      - '**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**'
      - '.github/workflows/**'

jobs:
  test:
    name: Test on Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22', '1.23', '1.24' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      # - name: Cache dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/go/pkg/mod
      #       go.sum
      #     key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

      - name: Download Go modules
        run: go mod download

      - name: Check formatting
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "Unformatted files:"
            echo "$unformatted"
            exit 1
          fi

      - name: Run tests
        run: go test -v
